name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    # Removed the test step since you don't want to run tests

    - name: Build Docker image
      run: docker build -t your-docker-username/simple-nodejs-app .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to DockerHub
      run: docker push your-docker-username/simple-nodejs-app

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull your-docker-username/simple-nodejs-app
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:3000 --name app your-docker-username/simple-nodejs-app
